//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShop.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderView
    {
        public int IdOrder { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<decimal> Sum { get; set; }
    }
}
